### ISSUE TITLE
Error in is.data.frame(frame) : object 'i4tb.pop' not found

### ISSUE THREAD

**Issue by joeflack4** [TB-Modeling/impaact4tb-tpt-3hp#1]
## Description
When running `i4tb_pop032920_sim.Rmd`, I get [an error at line 262](https://github.com/TB-Modeling/impaact4tb-tpt-3hp/blob/1ce53407835f2d891b6a81e51133b66c56f67069/r/i4tb_pop032920_sim.Rmd#L262):

`Error in is.data.frame(frame) : object 'i4tb.pop' not found`

### Screenshot 1
<img width="1280" alt="error" src="https://user-images.githubusercontent.com/13045020/90359145-1130a080-e026-11ea-9e21-ac1ee7fb7035.png">

### Additional investigation
I looked and I did not see any line where this variable `i4tb.pop` was created. I think that what might have happened is either one of (a) this variable was named something else, was renamed, but not renamed in all places, or (b) there were other variables that were in the R environment when producing this model, of which `i4tb.pop` was one, and that environment did not make it into our code here on Git, or (c) maybe the line where `i4tb.pop` was created accidentally got deleted.

Do we know what this variable is supposed to be and how it is supposed to be read / created?

**Comment by juliashinhj** [comment]
The line should have been deleted. I updated the code!

**Comment by joeflack4** [comment]
Fixed, thanks!
