### ISSUE TITLE
Error in paste0(a) : object 'a' not found

### ISSUE THREAD

**Issue by joeflack4** [TB-Modeling/impaact4tb-tpt-3hp#2]
## Description
When running `i4tb_pop032920_sim.Rmd`, I get [an error at line 411](https://github.com/TB-Modeling/impaact4tb-tpt-3hp/blob/0cff7c1f9e27cd5422a346063c09e5eb62618fa6/r/i4tb_pop032920_sim.Rmd#L411):

`Error in paste0(a) : object 'a' not found`

### Screenshot 1
<img width="1280" alt="error" src="https://user-images.githubusercontent.com/13045020/90368197-bb64f400-e037-11ea-87af-3c813fac2b3d.png">

I haven't done any follow-up investigation on this variable, `a`; I think it might have gotten deleted or renamed at some point?

**Comment by juliashinhj** [comment]
I added one command about 'a' in the beginning!

**Comment by joeflack4** [comment]
Ok cool. running now

**Comment by joeflack4** [comment]
성공!
